version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mentor_network
  app:
    container_name: mentor-backend-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${NODE_PORT}:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app/
    environment:
      - NODE_ENV=development
    # - DATABASE_URL=postgres://username:password@db:5432/dbname
    depends_on:
      - db
    command: yarn run start:dev
    networks:
      - mentor_network

volumes:
  postgres_data:

networks:
  mentor_network:
