const EVENTS = {
  NEW_CLIENT_NOTIFICATION: 'new_notification',
  NEW_COURSE: 'new_course',
  PAID_COURSE_SUB_SUCCESSFUL: 'PAID_COURSE_SUB_SUCCESSFUL',
  CANCEL_EXISTING_PAYMENT: 'CANCEL_EXISTING_PAYMENT',
};

export default EVENTS;
