const EVENTS = {
  NEW_CLIENT_NOTIFICATION: 'new_notification',
  NOTIFY_FOLLOWERS: 'NOTIFY_FOLLOWERS',
  NEW_COURSE: 'new_course',
  PAID_COURSE_SUB_SUCCESSFUL: 'PAID_COURSE_SUB_SUCCESSFUL',
  CANCEL_EXISTING_PAYMENT: 'CANCEL_EXISTING_PAYMENT',
  APPOINTMENT_PAYMENT_CONFIRMED: 'appointment_payment_confirmed',
  CANCEL_APPOINTMENT: 'CANCEL_APPOINTMENT',
  MENTOR_ACCEPT_APPOINTMENT: 'mentor_accept_appointment',
  APPOINTMENT_RESCHEDULE: 'appointment_reschedule',
};

export default EVENTS;
